# Generated by Django 5.2.4 on 2025-12-01 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evalution_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('evaluation_period', models.CharField(help_text='Evaluation period of the assessment', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Name_of_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('describtion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('designation', models.CharField(choices=[('NURSING_OFFICER', 'Nursing Officer'), ('SENIOR_NURSING_OFFICER', 'Senior Nursing Officer'), ('NURSING_AID', 'Nursing AID')], default='NURSING_OFFICER', max_length=150)),
                ('date_of_join', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Form1_assement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('data', models.JSONField(default=dict)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('approved_evalutor_id', models.CharField(blank=True, max_length=6, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('staff_acknowdged', models.BooleanField(default=False)),
                ('evaluation_year', models.IntegerField(default=2025)),
                ('evaluation_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='nursing_department.evalution_period')),
            ],
            options={
                'ordering': ['-evaluation_date'],
            },
        ),
    ]
