# Generated by Django 5.2.4 on 2025-12-01 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursing_department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='form1_assement',
            name='evaluator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form1_assement',
            name='form_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nursing_department.name_of_form'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form1_assement',
            name='staff_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='nursing_department.staffprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='form1_assement',
            unique_together={('staff_profile', 'evaluation_period')},
        ),
    ]
