"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iydz)#d$4*h4duwl#9$u$l=pqz3@w=4&7auwsq@)rxx54$4ke8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['172.16.20.114', '127.0.0.1', 'localhost']
#



# Application definition
CSRF_TRUSTED_ORIGINS = [
    "http://172.16.20.114:8002",
    "http://127.0.0.1:8002",
    "http://localhost:8002",
]



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'nursing_department',
    'front_office',
    'hr_department',
    'it_department',
    "tailwind",
    "theme",
]

TAILWIND_APP_NAME = 'theme'
# INTERNAL_IPS = ["127.0.0.1"]    


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]





ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

AUTH_USER_MODEL = 'users.Employee'



DATE_INPUT_FORMATS = [
    '%d/%m/%Y',   # 15/02/2025
    '%Y-%m-%d',   # 2025-02-15 (browser default)
]



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'nursing_assessment',        # Your database name
        'USER': 'postgres',     # Your Postgres user
        'PASSWORD': 'his',  # Replace with actual password
        'HOST': 'localhost',    # Or IP if remote
        'PORT': '5432',         # Default Postgres port
    }
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'handlers': {
        'registration_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'registration.log',  # File will be created in project root
            'formatter': 'simple',
        },
    },

    'formatters': {
        'simple': {
            'format': '[{asctime}] {levelname} {message}',
            'style': '{',
        },
    },

    'loggers': {
        'registration_logger': {
            'handlers': ['registration_file'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

import os

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SESSION_COOKIE_AGE = 6000 # seconds
SESSION_SAVE_EVERY_REQUEST = True

LOGIN_URL = '/login/'



AUTH_USER_MODEL = 'users.Employee'  # Point to your custom model


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # Add any custom backends if needed
]


SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False




STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}