# Generated by Django 5.2.4 on 2025-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='It_Department_Main_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('mail_send', models.BooleanField(default=False)),
                ('privilege', models.BooleanField(default=False)),
                ('credentials_setup', models.BooleanField(default=False)),
                ('whats_app_link', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
