# Generated by Django 5.2.4 on 2025-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hr_Department_Main_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('soft_delete', models.BooleanField(default=False)),
                ('iqraa_id', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('designation', models.CharField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=254)),
                ('employee_category', models.CharField(blank=True, max_length=254)),
                ('mobile_phone', models.CharField(choices=[('ANDROID', 'ANDROID'), ('IPHONE', 'IPHONE')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
